version: "3"
services:
  app:
    hostname: hatoka-poker-app
    image: "local/hatoka/poker-app:latest"
    ports:
      - "4200:80"
    volumes:
      - ./app/src/assets/config:/usr/share/nginx/html/assets/config
